# Generated by Django 5.2.17 on 2026-08-20 07:38

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=accounts.models.generate_invite_code, help_text='The secret in the signup URL. Leave blank to generate one.', max_length=64, unique=True)),
                ('label', models.CharField(blank=True, help_text="What this invite is for, e.g. 'Dave — rope access trial'", max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to revoke this invite immediately.')),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='How many accounts this invite may create. 0 means unlimited.')),
                ('uses', models.PositiveIntegerField(default=0, editable=False)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional. After this moment the invite stops working.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
