# Generated by Django 5.2.17 on 2026-09-12 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_invite'),
        ('sites', '0004_client_onboarding_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='client_name',
            field=models.CharField(blank=True, help_text="Name for the workspace this invite creates, e.g. 'Summit Rope Access Ltd'. Leave blank to derive one from whoever signs up. Ignored when joining an existing client.", max_length=200),
        ),
        migrations.AddField(
            model_name='invite',
            name='creates_sandbox',
            field=models.BooleanField(default=True, help_text="On: a trial workspace, named '<their name> (Sandbox)'. Off: a real client workspace — use this for a paying client, and set the client name below."),
        ),
        migrations.AddField(
            model_name='invite',
            name='existing_client',
            field=models.ForeignKey(blank=True, help_text='Join this existing client instead of creating a workspace. This is how a client brings colleagues in — set max uses to the size of the team, or 0 for unlimited.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='sites.client'),
        ),
        migrations.AddField(
            model_name='invite',
            name='granted_role',
            field=models.CharField(choices=[('client_admin', 'Client Admin'), ('client_user', 'Client User')], default='client_admin', help_text='Client Admin can manage sites and thresholds. Client User is read-only — the right choice for a colleague joining an existing client. Superadmin is deliberately not offered.', max_length=20),
        ),
        migrations.AddField(
            model_name='invite',
            name='site_limit',
            field=models.PositiveIntegerField(default=0, help_text='Active site cap for the workspace this invite creates. 0 falls back to SANDBOX_MAX_SITES. Ignored when joining an existing client, whose own limit applies.'),
        ),
    ]
