"""
OrcaMet Portal — Forecast Models

ForecastRun: A single execution of the forecast engine for a site.
HourlyForecast: Individual hourly data points within a run.
UKRiskMap: Stores generated UK-wide risk map images.
"""

from django.db import models
from django.utils import timezone


class ForecastRun(models.Model):
    """
    A single forecast generation run for a specific site.
    Created twice daily by the cron job.
    """

    class Status(models.TextChoices):
        PENDING = "pending", "Pending"
        RUNNING = "running", "Running"
        SUCCESS = "success", "Success"
        FAILED = "failed", "Failed"

    site = models.ForeignKey(
        "sites.Site",
        on_delete=models.CASCADE,
        related_name="forecast_runs",
    )
    status = models.CharField(
        max_length=10,
        choices=Status.choices,
        default=Status.PENDING,
    )
    forecast_date = models.DateField(
        help_text="The date this forecast is valid for",
    )
    generated_at = models.DateTimeField(default=timezone.now)

    # Summary statistics for quick display
    peak_risk = models.FloatField(null=True, blank=True, help_text="Peak risk % for the day")
    recommendation = models.CharField(max_length=20, blank=True, help_text="GO / CAUTION / CANCEL")
    peak_wind = models.FloatField(null=True, blank=True, help_text="Peak wind speed (m/s)")
    peak_gust = models.FloatField(null=True, blank=True, help_text="Peak gust (m/s)")
    peak_precip = models.FloatField(null=True, blank=True, help_text="Peak precipitation (mm/h)")
    min_temp = models.FloatField(null=True, blank=True, help_text="Minimum temperature (°C)")

    # Models used in ensemble
    models_used = models.JSONField(default=list, help_text="List of weather model names used")

    # Optional: stored chart image as base64 or file path
    chart_image = models.TextField(blank=True, help_text="Base64-encoded forecast chart PNG")
    text_report = models.TextField(blank=True, help_text="Generated text report")

    # Threshold snapshot (so we know what thresholds were active when forecast was generated)
    thresholds_snapshot = models.JSONField(
        default=dict,
        help_text="Copy of threshold values used for this forecast run",
    )

    error_message = models.TextField(blank=True)

    class Meta:
        ordering = ["-generated_at"]
        # One forecast per site per date per run
        unique_together = ["site", "forecast_date", "generated_at"]

    def __str__(self):
        return f"{self.site.name} — {self.forecast_date} — {self.get_status_display()}"


class HourlyForecast(models.Model):
    """Individual hourly forecast data point within a run."""

    run = models.ForeignKey(
        ForecastRun,
        on_delete=models.CASCADE,
        related_name="hourly_data",
    )
    timestamp = models.DateTimeField()

    # Ensemble-blended values
    wind_speed = models.FloatField(help_text="Ensemble mean wind speed (m/s)")
    wind_gusts = models.FloatField(help_text="Ensemble mean gusts (m/s)")
    precipitation = models.FloatField(help_text="Ensemble mean precipitation (mm/h)")
    temperature = models.FloatField(help_text="Ensemble mean temperature (°C)")

    # Model spread (uncertainty)
    wind_spread = models.FloatField(default=0.0)
    gust_spread = models.FloatField(default=0.0)
    precip_spread = models.FloatField(default=0.0)
    temp_spread = models.FloatField(default=0.0)

    # Computed risk
    hourly_risk = models.FloatField(help_text="Risk score 0-100%")

    class Meta:
        ordering = ["timestamp"]

    def __str__(self):
        return f"{self.run.site.name} — {self.timestamp:%H:%M} — Risk: {self.hourly_risk:.0f}%"


class UKRiskMap(models.Model):
    """Stores UK-wide risk map images generated by the map script."""

    forecast_date = models.DateField()
    generated_at = models.DateTimeField(default=timezone.now)
    image_data = models.TextField(help_text="Base64-encoded PNG of UK risk map")
    peak_risk = models.FloatField(null=True, blank=True)
    peak_location_lat = models.FloatField(null=True, blank=True)
    peak_location_lon = models.FloatField(null=True, blank=True)
    grid_points = models.IntegerField(default=0)

    class Meta:
        ordering = ["-generated_at"]

    def __str__(self):
        return f"UK Risk Map — {self.forecast_date}"
