# Generated by Django 5.2.16 on 2026-08-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0002_ukriskgridrun_ukriskgridpoint_cachedcontourimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UKRiskMap',
        ),
    ]
