# Generated by Django 5.2.17 on 2026-08-20 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0003_delete_ukriskmap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapThresholds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind_mean_caution', models.FloatField(default=10.0, help_text='Wind caution threshold (m/s)')),
                ('wind_mean_cancel', models.FloatField(default=14.0, help_text='Wind cancel threshold (m/s)')),
                ('gust_caution', models.FloatField(default=15.0, help_text='Gust caution threshold (m/s)')),
                ('gust_cancel', models.FloatField(default=20.0, help_text='Gust cancel threshold (m/s)')),
                ('precip_caution', models.FloatField(default=0.7, help_text='Precipitation caution (mm/h)')),
                ('precip_cancel', models.FloatField(default=2.0, help_text='Precipitation cancel (mm/h)')),
                ('temp_min_caution', models.FloatField(default=1.0, help_text='Temperature caution (°C)')),
                ('temp_min_cancel', models.FloatField(default=-2.0, help_text='Temperature cancel (°C)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UK map risk thresholds',
                'verbose_name_plural': 'UK map risk thresholds',
            },
        ),
    ]
