# Generated by Django 5.2.17 on 2026-08-20 09:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0005_mapthresholds_temp_max_cancel_and_more'),
        ('sites', '0003_thresholdprofile_temp_max_cancel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastLock',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='forecast_lock', serialize=False, to='sites.site')),
                ('acquired_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('holder', models.CharField(blank=True, help_text='host:pid that took the lock, for diagnosing a stuck run', max_length=120)),
            ],
            options={
                'verbose_name': 'forecast lock',
            },
        ),
        migrations.AddIndex(
            model_name='forecastrun',
            index=models.Index(fields=['site', 'status', 'forecast_date'], name='forecasts_site_status_date_idx'),
        ),
    ]
