# Generated by Django 5.2.17 on 2026-08-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0006_forecastlock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastrun',
            name='ensemble_members',
            field=models.PositiveIntegerField(blank=True, help_text='How many members backed the probabilities (provenance)', null=True),
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='limiting_variable',
            field=models.CharField(blank=True, help_text='gust, wind, precip or temperature — whichever breached worst', max_length=20),
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='max_temp',
            field=models.FloatField(blank=True, help_text="Maximum temperature (°C). Needed since heat thresholds exist — without it a hot day's verdict has no visible explanation.", null=True),
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='p_cancel',
            field=models.FloatField(blank=True, help_text='Share of ensemble members breaching any cancel limit in the work window', null=True),
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='p_cancel_by_variable',
            field=models.JSONField(blank=True, default=dict, help_text='Breakdown of p_cancel by the limit that was breached'),
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='p_caution',
            field=models.FloatField(blank=True, help_text='Share of members breaching any caution limit', null=True),
        ),
        migrations.AddField(
            model_name='hourlyforecast',
            name='percentiles',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
