# Generated by Django 5.2.17 on 2026-08-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0007_forecastrun_ensemble_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ukriskgridpoint',
            name='ensemble_members',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Members backing p_cancel at this point', null=True),
        ),
        migrations.AddField(
            model_name='ukriskgridpoint',
            name='p_cancel',
            field=models.FloatField(blank=True, help_text='Chance of cancellation at this hour, 0-100%', null=True),
        ),
        migrations.AlterField(
            model_name='cachedcontourimage',
            name='variable',
            field=models.CharField(choices=[('pcancel', 'Chance of Cancellation'), ('risk', 'Risk'), ('wind', 'Wind Speed'), ('gust', 'Wind Gusts'), ('precip', 'Precipitation'), ('temp', 'Temperature')], max_length=10),
        ),
    ]
