# Generated by Django 5.2.17 on 2026-09-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0009_correct_grid_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='ukriskgridpoint',
            name='wind_direction',
            field=models.FloatField(blank=True, help_text='Direction the wind comes FROM, degrees from true north', null=True),
        ),
        migrations.AddField(
            model_name='ukriskgridpoint',
            name='wind_direction_agreement',
            field=models.FloatField(blank=True, help_text='Member agreement on direction, 0 (none) to 1 (unanimous)', null=True),
        ),
    ]
