# Generated by Django 6.0.2 on 2026-02-27 12:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('postcode', models.CharField(help_text='UK postcode — will be automatically geocoded to lat/lon', max_length=10)),
                ('latitude', models.FloatField(blank=True, help_text='Auto-populated from postcode via postcodes.io', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Auto-populated from postcode via postcodes.io', null=True)),
                ('elevation', models.IntegerField(default=0, help_text='Elevation in metres above sea level')),
                ('exposure', models.CharField(choices=[('urban', 'Urban'), ('coastal', 'Coastal'), ('highland', 'Highland'), ('rural', 'Rural')], default='urban', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('job_complete', models.BooleanField(default=False, help_text='When True, forecast generation stops for this site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.client')),
            ],
            options={
                'ordering': ['client', 'name'],
                'unique_together': {('client', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('site_created', 'Site Created'), ('site_updated', 'Site Updated'), ('site_deactivated', 'Site Deactivated'), ('threshold_created', 'Threshold Created'), ('threshold_updated', 'Threshold Updated')], max_length=30)),
                ('details', models.JSONField(default=dict, help_text='JSON object describing what changed')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelog', to='sites.site')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ThresholdProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('wind_mean_caution', models.FloatField(default=10.0, help_text='Wind caution threshold (m/s)')),
                ('wind_mean_cancel', models.FloatField(default=14.0, help_text='Wind cancel threshold (m/s)')),
                ('gust_caution', models.FloatField(default=15.0, help_text='Gust caution threshold (m/s)')),
                ('gust_cancel', models.FloatField(default=20.0, help_text='Gust cancel threshold (m/s)')),
                ('precip_caution', models.FloatField(default=0.7, help_text='Precipitation caution (mm/h)')),
                ('precip_cancel', models.FloatField(default=2.0, help_text='Precipitation cancel (mm/h)')),
                ('temp_min_caution', models.FloatField(default=1.0, help_text='Temperature caution (°C)')),
                ('temp_min_cancel', models.FloatField(default=-2.0, help_text='Temperature cancel (°C)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='sites.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
