# Generated by Django 5.2.17 on 2026-08-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_sandbox',
            field=models.BooleanField(default=False, help_text='A private trial workspace created by an invite link, not a real paying client. Sandbox owners may add and edit their own sites through the portal, subject to SANDBOX_MAX_SITES.'),
        ),
    ]
