# Generated by Django 5.2.17 on 2026-08-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_client_is_sandbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='thresholdprofile',
            name='temp_max_cancel',
            field=models.FloatField(blank=True, default=32.0, help_text='Heat cancel threshold (°C). Leave blank to ignore heat for this site.', null=True),
        ),
        migrations.AddField(
            model_name='thresholdprofile',
            name='temp_max_caution',
            field=models.FloatField(blank=True, default=27.0, help_text='Heat caution threshold (°C). Leave blank to ignore heat for this site.', null=True),
        ),
        migrations.AlterField(
            model_name='thresholdprofile',
            name='temp_min_cancel',
            field=models.FloatField(default=-2.0, help_text='Cold cancel threshold (°C)'),
        ),
        migrations.AlterField(
            model_name='thresholdprofile',
            name='temp_min_caution',
            field=models.FloatField(default=1.0, help_text='Cold caution threshold (°C)'),
        ),
    ]
