# Generated by Django 5.2.17 on 2026-09-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_thresholdprofile_temp_max_cancel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, help_text='When the workspace finished the onboarding wizard. Blank means an admin logging in is sent to the wizard instead of the dashboard. Clear it to make them walk through it again.', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='self_service_sites',
            field=models.BooleanField(default=False, help_text="Let this client's admins add, edit and import their own sites through the portal. Off by default: staff-managed clients are administered here, in the Django admin. Granted by the invite that provisions a workspace."),
        ),
        migrations.AddField(
            model_name='client',
            name='site_limit',
            field=models.PositiveIntegerField(default=0, help_text="Maximum active sites this client may create for itself. 0 falls back to SANDBOX_MAX_SITES. Ignored unless 'self service sites' is on — staff-created sites are never capped."),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_sandbox',
            field=models.BooleanField(default=False, help_text="A private trial workspace created by an invite link, not a real paying client. Affects wording only — whether the workspace may manage its own sites is controlled by 'self service sites'."),
        ),
    ]
