# Generated by Django 5.2.17 on 2026-09-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_grant_self_service_to_sandboxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='default_exposure',
            field=models.CharField(blank=True, help_text='Exposure given to imported sites that do not name one, and pre-selected when adding a site by hand. Blank means Urban.', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='threshold_preset',
            field=models.CharField(blank=True, help_text='Starting weather limits applied to new sites. Blank uses the standard rope access preset. Changing this does not touch existing sites — their thresholds are edited per site.', max_length=40),
        ),
    ]
